/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xiaozhou233_OrangeX_JNI_NativeDll */

#ifndef _Included_cn_xiaozhou233_OrangeX_JNI_NativeDll
#define _Included_cn_xiaozhou233_OrangeX_JNI_NativeDll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xiaozhou233_OrangeX_JNI_NativeDll
 * Method:    inject
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_OrangeX_JNI_NativeDll_inject
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
